TRANSPARENT = (0, 0, 1)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
PINK = (255, 102, 204)

DECKS = [
    {"name" : "main",
        "pos" : (1, 1),
        "size" : 200,
        "movable" : False},
    {"name" : "discard",
        "pos" : (2, 1),
        "size" : 200,
        "movable" : False},
    {"name" : "hearts",
        "pos" : (4, 1),
        "size" : 200,
        "movable" : False},
    {"name" : "diamonds",
        "pos" : (5, 1),
        "size" : 200,
        "movable" : False},
    {"name" : "spades",
        "pos" : (6, 1),
        "size" : 200,
        "movable" : False},
    {"name" : "clubs",
        "pos" : (7, 1),
        "size" : 200,
        "movable" : False},
    {"name" : "game1",
        "pos" : (1, 2),
        "size" : 200,
        "movable" : False},
    {"name" : "game2",
        "pos" : (2, 2),
        "size" : 200,
        "movable" : False},
    {"name" : "game3",
        "pos" : (3, 2),
        "size" : 200,
        "movable" : False},
    {"name" : "game4",
        "pos" : (4, 2),
        "size" : 200,
        "movable" : False},
    {"name" : "game5",
        "pos" : (5, 2),
        "size" : 200,
        "movable" : False},
    {"name" : "game6",
        "pos" : (6, 2),
        "size" : 200,
        "movable" : False},
    {"name" : "game7",
        "pos" : (7, 2),
        "size" : 200,
        "movable" : False},
    {"name": 'mobile',
        'pos': (0,0),
        'size': 200,
        "movable" : True}
]
